apiVersion: v1
kind: Namespace
metadata:
  name: sealedissuer
---
apiVersion: v1
data:
## kubectl get secret -n kube-system -l sealedsecrets.bitnami.com/sealed-secrets-key  -o yaml
  cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVyVENDQXBXZ0F3SUJBZ0lRWXVUeDE4ZDBhdHhkVEljVUVrUWFNVEFOQmdrcWhraUc5dzBCQVFzRkFEQUEKTUI0WERUSXhNRGd5TXpFME1qTXpPVm9YRFRNeE1EZ3lNVEUwTWpNek9Wb3dBRENDQWlJd0RRWUpLb1pJaHZjTgpBUUVCQlFBRGdnSVBBRENDQWdvQ2dnSUJBTGVldTRmeE02bHJwUlVIUTI2c3htdGpHS2lpb0FmbkRSZ0pLUi9IClEwcExjODdMZWk0M3d6QVI1emNKUkxEeEZkWjFDRGxoSXRtcXJiWGlNWTBGQUMwakNEWktRY2kxSUxGVEdXd1oKNTg0M2V0UFdIYTVXbDVWVUFIMVdoa2M2VWJvQWJ2MFVnb1NQMTVDMEdsN1huOUdnUjZNNm1QbHJPRklRWjJFcgpTbE9aTWRUMWRuajh4QTgvdWw2a2l0c1ZkcHFUSmVrcDk3TnNSN25mYUpUNFczb3ZIL01vTys1NGFjUGtDSDJiClAxUXhUTGFBYm93NkxhNmtNdzU0RWtHZlRNbXJTU2gzdTRyaVd0cExpd0ZmVGlJZERuc0kwZW0zcmRrdGsvR20KY0UybWdrWWI1Z2tONzZYQ2hOakRLZkF4MzlJK2tRMHVEdHhVdExXZEczS0hJSUFERFowNkFTdmRLcGxRS2VZWQo3aDVuVExaUEZJRFp1RHhIbG1MajZaV1BRcjBJSzNKNm9IVEJLbGtIdmNYUWt1UDYvd0IzbFMvTzRKZDk4aGtWCmpQMDl1MkhKS00zLzdKWENzV3dIK1dDazEyTWZEYlFtaHJSSVFNMTg4dVlaVTZPaWJjeEU4K3BtazZoUnQwbkIKWEtibG1Gc0J6ZkJCY25zb2xWVEJKVGxBV05DZFl5RXhTeWVaNFlxUDlJZkNGbzVNbkFmZUdhVnhhSVdyZXA0VwpaUDdiNTRpUDNYV0JVeFlVQ2VJSmt1OGdhSHdpaDdMYVpmZGtYSGpjdThBVUFpSTExVFVWWDROeEJNYjFYM0ZmCm5nUHZNTEMxT2tsRE9sUEpSTUZvZm1KQ21mTWI4Ujhna3ZiNDQ2eWdhWjdHVW1PQ0dSeHBZVExTWktDYUJTMG4KT1dkMUFnTUJBQUdqSXpBaE1BNEdBMVVkRHdFQi93UUVBd0lBQVRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQnVFVEpuNmhjWUxYblVvaE16SU1yZUJpQVR4eUVTZ0M3M2RYdkh2YmR3CmhmTkFLRDEwM0k4eTJ1cktEUkJ1dDRFT0JwbDhKVndRRFBWS05vNjNMTXJCTzFTM3lqRHgyaVFYODJ0UW5mU0IKaXlyZW5kSi9wVXNtUkJnMWxDQ0UxVmwva0xkT2ZPdk1OTUhoWFVHVDhjWG1mUHpIZ0dlTE5WZnZCN3g4MlUzaQphbGE0OUs0Z1o5UnJtblpQbzZPTUk2MHQ0M2MrMnJJQmwwVFM2Zm41cVAzRGhoOUwrVzhnMDg2Mkh2WUJDLzlaCkp4QmNaRUNpbnZKUml5em1xRkI5M2RPL3BHaWNCcDNncGRWREVRVmlkUmMwUzZkMWZxWDU1UkwxWWFrY01RcWsKTkRreUFGbWhwRXZiMko2bW9abWR5K29KR3o3VXpkUlJSUFBxbjdFQ0EyTlpVVmhnc01vTDhiVERmR1ZXeDduUworRVdtb2hlQUttK2pZQ1JGaUw2WElWdTc5cklKcG1wQ0xNVDVYckV6dnM1YUZGZ3NHbTd6d0JndjFULzJ5c3ZoCit6dnZpNFdRUmhEK2h0S1EvNGdVV29VOVNVYmR0RnpWRWliRUM2UGM2MDN0NG5TZHozVHQvOW5MREc5bmQ0b1EKa3NJTnV1MmFnS2FwNUtycFlpQUZvUU1KaFBZZ0YrL0RRdE44ZUd4T3hWYVRWVHI2TjdUVTdTVmk1NVV1Qy96dQpzMUZxc21CNEIvNmViTTNrMEQvOW1Ba2pnVUl1VThlV1QrcXlYOGFwNXRobFBPMjJFNmxJN3FPZThyNWFqYWMwCkI3NWppNDRqQWFNaC9WdGN1RHdnMXhDNlhQTGFocHJrSXpxUGxHb3FGbzBTeWoyL0VndFNVQXdEajlWUWhjMTAKbkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
kind: Secret
metadata:
  name: sealedissuer-certificate
  namespace: sealedissuer
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealedissuer-deployment
  namespace: sealedissuer
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: sealedissuer-frontend
  template:
    metadata:
      labels:
        app: sealedissuer-frontend
    spec:
      volumes:
        - name: certificate-file
          secret:
            secretName: sealedissuer-certificate
      containers:
        - name: sealedissuer
          image: registry.gitlab.com/genral73/k8s-tools/sealedsecret-issuer:latest
          volumeMounts:
            - name: certificate-file
              mountPath: /kubeseal/cert.pem
              subPath: cert.pem
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.2"
              memory: "50Mi"
            limits:
              cpu: "0.25"
              memory: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: sealedissuer-svc
  namespace: sealedissuer  
spec:
  type: ClusterIP
  selector:
    app: sealedissuer-frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
  name: sealedissuer-ingress
  namespace: sealedissuer
spec:
  rules:
    - host: sealedissuer.localhost
      http:
        paths:
          - backend:
              serviceName: sealedissuer-svc
              servicePort: http
            path: /