apiVersion: v1
kind: Secret
metadata:
  name: darkstore-odoo-dbinfo-secret
data:
  POSTGRES_HOST: MTcyLjE3LjAuMQ==
  POSTGRES_DB: azhzX2tfZGV2X2RhcmtzdG9yZQ==
  POSTGRES_USER: azhzLWRhcmtzdG9yZS1kZXY=
  POSTGRES_PASSWORD: djZ5SEVDSkx2ajNTcUtDVXRTUEpIOE1SV3hzaGdn
  POSTGRES_PORT: NTQzMg==
