apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: k8s-resources
  source:
    repoURL: 'https://github.com/genral73/k8s-kind.git'
    path: k8s-resources/tools/ingress-nginx
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: k8s-resources
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---      
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: k8s-resources
  source:
    repoURL: 'https://github.com/genral73/k8s-kind.git'
    path: k8s-resources/tools/metrics-server
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: k8s-resources
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealedsecret-issuer
  namespace: argocd
spec:
  project: k8s-resources
  source:
    repoURL: 'https://github.com/genral73/k8s-kind.git'
    path: k8s-resources/tools/sealedsecret-issuer
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml      
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: k8s-resources
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: k8s-resources
  source:
    repoURL: 'https://github.com/genral73/k8s-kind.git'
    path: k8s-resources/tools/minio
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: k8s-resources
  syncPolicy:
    automated:
      prune: true
      selfHeal: true