apiVersion: v1
kind: Namespace
metadata:
  name: k8s-tools
  labels:
    environment: k8s-cluster
---
apiVersion: v1
kind: Secret
data:
  password: Z2hwX1E5cmVCalVsWXkzNHJaZ2M4TXVPMk4wSFBMWWpNRDRib05sZw==
  username: Z2VucmFsNzM=
metadata:
  name: github-reg-cred
  namespace: argocd
type: Opaque
---
apiVersion: v1
kind: Secret
data:
  password: RE9kbzA5MDk2OTk1MTU=
  username: Z2VucmFsNzM=
metadata:
  name: gitlab-reg-cred
  namespace: argocd
type: Opaque
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: k8s-tools-resources-quota
  namespace: k8s-tools
spec:
  hard:
    limits.cpu: "4000m"
    limits.memory: 12Gi
    count/pods: "32"
    count/services: "16"
    count/secrets: "16"
    count/configmaps: "16"
    count/deployments.apps: "16"
    count/replicasets.apps: "16"
    count/statefulsets.apps: "16"
    count/jobs.batch: "16"
    count/cronjobs.batch: "16"
    count/deployments.extensions: "16"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: k8s-tools-limit-range
  namespace: k8s-tools
spec:
  limits:
  - default:
      memory: 264Mi
      cpu: 200m
    defaultRequest:
      memory: 128Mi
      cpu: 100m
    type: Container
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: k8s-tools
imagePullSecrets:
- name: github-reg-cred
- name: gitlab-reg-cred
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-tools-root-psp
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:restricted
subjects:
- kind: ServiceAccount
  name: default
  namespace: k8s-tools
---
# apiVersion: rbacmanager.reactiveops.io/v1beta1
# kind: RBACDefinition
# metadata:
#   name: k8s-tools-app-operators
# rbacBindings:
#   - name: users
#     subjects:
#       - kind: User
#         name: "dafaallah"
#     roleBindings:
#       - namespace: "k8s-tools"
#         clusterRole: app-operator
# ---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-tools
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: k8s Cluster Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: k8s-tools
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  # namespaceResourceBlacklist:
  # - group: ''
  #   kind: ResourceQuota
  # - group: ''
  #   kind: LimitRange
  # - group: ''
  #   kind: NetworkPolicy
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
#  - group: 'apps'
#    kind: StatefulSet
  orphanedResources:
    warn: false
  roles:
  - name: k8s-operator
    description: Read-only privileges to k8s-tools
    policies:
    - p, proj:k8s-tools:k8s-operator, applications, *, k8s-tools/*, allow
    groups:
    - dafaallah
    - admin
    jwtTokens:
    - iat: 1604331144
      id: 6c276c70-0f97-4d22-aac9-20123242e25c
---      
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-tools-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/genral73/k8s-kind.git'
    path: k8s-tools-config
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: k8s-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true